server:
  port: 8080
  shutdown: graceful

spring:
  application.name: ${KUBE_POD:banksim}
  profiles:
    active: "local"
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    url: jdbc:postgresql://${DATABASE_SERVER_NAME:localhost}:${DATABASE_SERVER_PORT:5432}/${DATABASE_NAME:postgres}
    username: ${DATABASE_USER_NAME:postgres}
    password: ${DATABASE_USER_PASSWORD:postgres}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud.stream:
    function:
      definition: stockQuoteListener
    bindings:
      stockQuoteListener-in-0:
        destination: streaming.bankbroker.stockquote.updated
    kafka:
      binder:
        brokers: kafka:9092
      bindings:
        stockQuoteListener-in-0:
          consumer:
            configuration:
              schema.registry.url: http://schema-registry:8081
              value:
                deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
              key:
                deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      streams:
        binder:
          configuration:
            schema.registry.url: http://schema-registry:8081