apiVersion: v1
kind: Service
metadata:
  name: balance
  namespace: bankbroker
  labels:
    app: balance
spec:
  selector:
    app: balance
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance
  namespace: bankbroker
spec:
  selector:
    matchLabels:
      app: balance
  replicas: 3
  template:
    metadata:
      labels:
        app: balance
    spec:
      containers:
        - name: balance
          image: balance:0.1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
