apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: bankbroker
  labels:
    app: zookeeper
    tier: backend
    role: kafka
spec:
  selector:
    app: zookeeper
    tier: backend
    role: kafka
  ports:
    - port: 2181
      targetPort: 2181
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: bankbroker
spec:
  selector:
    matchLabels:
      app: zookeeper
      tier: backend
      role: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
        tier: backend
        role: kafka
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:3.7.0-debian-10-r64
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          ports:
            - containerPort: 2181
